# These are supported funding model platforms

patreon: matomo
open_collective: matomo-analytics
ko_fi: matomo
liberapay: Matomo
custom: ['https://www.paypal.com/donate/?hosted_button_id=RPL23NJURMTFA']
